### ISSUE TITLE
Starting lona from a coroutine

### ISSUE THREAD

**Issue by laundmo** [lona-web-org/lona#196]
Currently, app.run cannot be run from a coroutine
```py
import asyncio
from lona import LonaView, LonaApp
from lona.html import HTML

app = LonaApp(__file__)


@app.route("/")
class Test(LonaView):
    def handle_request(self, request):
        self.show(HTML("bruh"))


async def main():
    app.run(loop=asyncio.get_event_loop(), port=8080)


asyncio.run(main())
```

i has assumed passing loop= in would work, but the error thrown is the same.

```
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\aiohttp\web.py", line 508, in run_app
    loop.run_until_complete(main_task)
  File "C:\Python39\lib\asyncio\base_events.py", line 618, in run_until_complete
    self._check_running()
  File "C:\Python39\lib\asyncio\base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\lauri\Documents\python-projects\games\northstar-webui\t.py", line 28, in <module>
    asyncio.run(main())
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "d:\lauri\Documents\python-projects\games\northstar-webui\t.py", line 21, in main
    app.run(loop=asyncio.get_event_loop(), port=8080)
  File "C:\Python39\lib\site-packages\lona\app.py", line 462, in run
    run_server(
  File "C:\Python39\lib\site-packages\lona\command_line\run_server.py", line 122, in run_server
    _run_app()
  File "C:\Python39\lib\site-packages\lona\command_line\run_server.py", line 90, in _run_app
    run_app(**keyword_args)
  File "C:\Python39\lib\site-packages\aiohttp\web.py", line 512, in run_app
    _cancel_tasks({main_task}, loop)
  File "C:\Python39\lib\site-packages\aiohttp\web.py", line 443, in _cancel_tasks
    loop.run_until_complete(
  File "C:\Python39\lib\asyncio\base_events.py", line 618, in run_until_complete
    self._check_running()
  File "C:\Python39\lib\asyncio\base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

```

next, i tried running lona from a thread so that i could start my coroutine after. no luck there. 
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "d:\lauri\Documents\python-projects\games\northstar-webui\t.py", line 16, in startserver
    loop = asyncio.get_event_loop()
  File "C:\Python39\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.
```

So, the only option seems to be to run my asyncio code in its own thread.

**Comment by fscherf** [comment]
@laundmo ``LonaApp.run`` uses ``aiohttp.web.run_app`` internally, which creates an ioloop and starts it. To start a Lona app from a coroutine you would have to do the same as aiohttp using ``app.aiohttp_app``.

Out of curiosity: Why do you want to start a Lona app from a coroutine?

**Comment by laundmo** [comment]
> Out of curiosity: Why do you want to start a Lona app from a coroutine?

Im trying to use lona with some code that needs to constantly communicate with sockets, and for that needs to run in its own coroutine or thread, and the latter is unappealing for a variety of reasons.

Alternatively, maybe lona has some built-in way to handle background tasks? for now im starting them in their own thread, which works okay. it's just odd that app.run would take a loop parameter if that loop cant be running.

**Comment by fscherf** [comment]
Yes there is: middlewares have an ``on_startup`` hook that can be used to create background tasks.

The loop argument in ``app.run`` is only for testing purposes. If you use the ``lona_app_context`` pytest fixture ``loop`` is set to start an Lona server on top of pytest-aiohttp

**Comment by laundmo** [comment]
thank you, i'll check out middlewares for this.

**Comment by laundmo** [comment]
Thank you, middlewares definitely work. And they allow me to inject things into the request, which is very nice for getting the instances associated with the running tasks (janus queues) passed to the views.

**Comment by fscherf** [comment]
Great! :) 
Yes i agree. I am writing docs at the moment anyway, so i will add an cookbook article on how to start background tasks from middlewares.
