### ISSUE TITLE
Example code does not execute on windows10/python38

### ISSUE THREAD

**Issue by simcup** [lona-web-org/lona#203]
the example copy-pasted from the doc does not compile on windows 10/python 3.8.5 via associated IDLE
![Lona_fail_4](https://user-images.githubusercontent.com/959467/151145465-dd9c2ed3-4cb8-4a08-a9bf-af189c237e6f.png)

**Comment by fscherf** [comment]
@laundmo can you verify that?

**Comment by laundmo** [comment]
would be good to know which example this is.

**Comment by laundmo** [comment]
1. i was also hit with #202 since im at work right now where i didn't have lona installed.
2. after installing from git as recommended in #202 i can confirm this issue is happening with the basic README example lona script.

<details>
<summary> Error, matches original report </summary>

```
MainThread                     ERROR    12:36:02.730760 lona.client_pre_compiler exception raised while pre compiling js client
  Traceback (most recent call last):
    File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\lona\client_pre_compiler.py", line 57, in compile
      template = self.jinja2_env.get_template('lona.js')
    File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\jinja2\environment.py", line 997, in get_template
      return self._load_template(name, globals)
    File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\jinja2\environment.py", line 958, in _load_template
      template = self.loader.load(self, name, self.make_globals(globals))
    File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\jinja2\loaders.py", line 125, in load
      source, filename, uptodate = self.get_source(environment, name)
    File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\jinja2\loaders.py", line 214, in get_source
      raise TemplateNotFound(template)
  jinja2.exceptions.TemplateNotFound: lona.js
Traceback (most recent call last):
  File "g:\user\laurin\restructured-imports\t.py", line 30, in <module>
    app.run(port=8080)
  File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\lona\app.py", line 455, in run
    self.setup_server(
  File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\lona\app.py", line 405, in setup_server
    self.server = LonaServer(
  File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\lona\server.py", line 172, in __init__
    self._static_file_loader = StaticFileLoader(self)
  File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\lona\static_file_loader.py", line 49, in __init__
    self.style_tags_html: str = self.server.render_template(
  File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\lona\server.py", line 737, in render_template
    self._templating_engine.render_template(
  File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\lona\templating.py", line 134, in render_template
    template = self.get_template(template_name)
  File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\lona\templating.py", line 104, in get_template
    template = self.jinja2_env.get_template(template_name)
  File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\laurin\AppData\Roaming\Python\Python39\site-packages\jinja2\loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: lona/style_tags.html
```
</details>

**Comment by fscherf** [comment]
Hm. Sounds like another packaging problem. @laundmo could you try to find out which commit breaks the installation?

**Comment by fscherf** [comment]
@laundmo: I am not completely sure why this happens. It looks like a packaging problem to me. I would bet on ``MANIFEST.in`` but that wasn't touched in a while. Is this maybe an artifact from the ImportError in the ``__init__.py`` i had to fix twice?

**Comment by laundmo** [comment]
good news: this appears to be solved on 1.9 which was just released.

**Comment by fscherf** [comment]
\o/ Then my hypothesis was right. @simcup can you verify that? In this case we can close this issue

**Comment by simcup** [comment]
works fine in version 1.9
