### ISSUE TITLE
Fresh install in OSX / Windows not working

### ISSUE THREAD

**Issue by korantu** [lona-web-org/lona#207]
I am setting up new lona project;

from python:

`$ python --version`

```
Python 3.9.10
```

On OSX:
`echo "import platform; print(platform.platform())" | python`

```
macOS-12.1-x86_64-i386-64bit
```

Simplest install:
`$ pip install lona`

```
Collecting lona
  Using cached lona-1.9.tar.gz (74 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: aiohttp<4,>=3 in ./.venv/lib/python3.9/site-packages (from lona) (3.8.1)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.9/site-packages (from lona) (3.0.3)
Requirement already satisfied: rlpython in ./.venv/lib/python3.9/site-packages (from lona) (0.8.4)
Requirement already satisfied: typing-extensions in ./.venv/lib/python3.9/site-packages (from lona) (4.1.1)
Requirement already satisfied: attrs>=17.3.0 in ./.venv/lib/python3.9/site-packages (from aiohttp<4,>=3->lona) (21.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.venv/lib/python3.9/site-packages (from aiohttp<4,>=3->lona) (6.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in ./.venv/lib/python3.9/site-packages (from aiohttp<4,>=3->lona) (1.3.0)
Requirement already satisfied: aiosignal>=1.1.2 in ./.venv/lib/python3.9/site-packages (from aiohttp<4,>=3->lona) (1.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in ./.venv/lib/python3.9/site-packages (from aiohttp<4,>=3->lona) (1.7.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in ./.venv/lib/python3.9/site-packages (from aiohttp<4,>=3->lona) (2.0.12)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./.venv/lib/python3.9/site-packages (from aiohttp<4,>=3->lona) (4.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.9/site-packages (from jinja2->lona) (2.0.1)
Requirement already satisfied: idna>=2.0 in ./.venv/lib/python3.9/site-packages (from yarl<2.0,>=1.0->aiohttp<4,>=3->lona) (3.3)
Using legacy 'setup.py install' for lona, since package 'wheel' is not installed.
Installing collected packages: lona
  Running setup.py install for lona: started
  Running setup.py install for lona: finished with status 'done'
Successfully installed lona-1.9
```

Attempting import:
`$ echo "import lona" | python`

```
﻿﻿Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/lona/lona.py", line 1, in <module>
    from lona.html import HTML, Button, Div, H1
ModuleNotFoundError: No module named 'lona.html'; 'lona' is not a package
```

Works fine in Linux; Anywhere I can look to start figuring this out?

**Comment by fscherf** [comment]
Hi @korantu,

Strange! First thing you can try is removing the ``try except`` block from ``lona/__init__.py``. Maybe there is an unhandled exception somewhere.

**Comment by korantu** [comment]
My bad, I named lona program `lona.py` - and it was importing itself instead of actual lona library.

So this is not a bug.

Thank you, @fscherf
