### ISSUE TITLE
Lona client exceedes call stack on large table update.

### ISSUE THREAD

**Issue by lichtfeind** [lona-web-org/lona#496]
I am useing:
- lona: 1.15
- lona-picocss: 0.4.1

When updating a large table on a channel event the Lona client explodes.
It does not seem to happen when updating the html in the `handle_request()` method.

[minimal.zip](https://github.com/lona-web-org/lona/files/12889965/minimal.zip)

Firefox:
```
LonaWorker_0                   ERROR    16:41:21.027054 lona.view_runtime client error raised:
_remove_node@http://localhost:8080/static//_lona/client2/rendering-engine.js:104:14
_clean_node_cache/<@http://localhost:8080/static//_lona/client2/rendering-engine.js:169:18
_clean_node_cache@http://localhost:8080/static//_lona/client2/rendering-engine.js:164:21
_remove_node@http://localhost:8080/static//_lona/client2/rendering-engine.js:107:14

... repeating
```
![firefox](https://github.com/lona-web-org/lona/assets/2574984/e620a9dd-758d-46b3-86b2-d06f9e6cffc3)

Chrome:
```
LonaWorker_1                   ERROR    07:42:30.283726 lona.view_runtime client error raised:
RangeError: Maximum call stack size exceeded
    at Map.forEach (<anonymous>)
    at LonaRenderingEngine._clean_node_cache (http://localhost:8080/static//_lona/client2/rendering-engine.js:164:21)
    at LonaRenderingEngine._remove_node (http://localhost:8080/static//_lona/client2/rendering-engine.js:107:14)
    at http://localhost:8080/static//_lona/client2/rendering-engine.js:169:18
    at Map.forEach (<anonymous>)
    at LonaRenderingEngine._clean_node_cache (http://localhost:8080/static//_lona/client2/rendering-engine.js:164:21)
    at LonaRenderingEngine._remove_node (http://localhost:8080/static//_lona/client2/rendering-engine.js:107:14)
    at http://localhost:8080/static//_lona/client2/rendering-engine.js:169:18
    at Map.forEach (<anonymous>)
    at LonaRenderingEngine._clean_node_cache (http://localhost:8080/static//_lona/client2/rendering-engine.js:164:21)
```
![chrome](https://github.com/lona-web-org/lona/assets/2574984/2f9ec231-03db-44f5-883b-4b7bf434eb1c)

**Comment by fscherf** [comment]
Hi @lichtfeind!

Thanks for this detailed bug report. I can reproduce it on my system and will look into it as soon as I can.

**Comment by fscherf** [comment]
@lichtfeind: I found the problem and created #497. Could you verify wether my patch fixes your problem?

**Comment by lichtfeind** [comment]
Yes that seems to fix my issue. Thanks for the quick fix.
